name: Process Beer Data

on:
  push:
    paths:
      - 'beer.json'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Removed npm install since there is no package.json

      - name: Run beer processing script
        run: node transform.js

      - name: Commit and push changes
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Update data: ${timestamp}" || exit 0
          git push